import { Product } from './app/shared/models/Product';
import { Tag } from './app/shared/models/Tag';

export const sample_products: Product[] = [
    {
        id: '1',
        name: 'Mascara',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/1.png',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '2',
        name: 'Mascara',
        price: 4,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: false,
        stars: 4.0,
        imageUrl: 'assets/images/2.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '3',
        name: 'Mascara',
        price: 3,
        favorite: false,
        is_in_inventory: true,
        discountPrice: 1.5,
        stars: 3.5,
        imageUrl: 'assets/images/3.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '4',
        name: 'Mascara',
        price: 5,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/4.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '5',
        name: 'Mascara',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/5.png',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '6',
        name: 'Mascara',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: false,
        stars: 5.0,
        imageUrl: 'assets/images/6.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '7',
        name: 'Mascara',
        price: 4,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/7.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '8',
        name: 'Mascara',
        price: 2,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/8.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '9',
        name: 'Mascara',
        price: 2,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/9.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '10',
        name: 'Mascara',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/10.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Mascara'],
    },
    {
        id: '11',
        name: 'Lipstick',
        price: 6,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/11.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '12',
        name: 'Lipstick',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/12.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '13',
        name: 'Lipstick',
        price: 4,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/13.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '14',
        name: 'Lipstick',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/14.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '15',
        name: 'Lipstick',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/15.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '16',
        name: 'Lipstick',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/16.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '17',
        name: 'Lipstick',
        price: 5,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/17.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '18',
        name: 'Lipstick',
        price: 6,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/18.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '19',
        name: 'Lipstick',
        price: 2,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/19.png',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '20',
        name: 'Lipstick',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/20.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Lipstick'],
    },
    {
        id: '21',
        name: 'Moisturizing Lotion',
        price: 5,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/21.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '22',
        name: 'Moisturizing Lotion',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/22.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '23',
        name: 'Moisturizing Lotion',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/23.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '24',
        name: 'Moisturizing Lotion',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/24.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '25',
        name: 'Moisturizing Lotion',
        price: 5,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 3.5,
        imageUrl: 'assets/images/25.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '26',
        name: 'Moisturizing Lotion',
        price: 6,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/26.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '27',
        name: 'Moisturizing Lotion',
        price: 8,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/27.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '28',
        name: 'Moisturizing Lotion',
        price: 6,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/28.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '29',
        name: 'Moisturizing Lotion',
        price: 7,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/29.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '30',
        name: 'Moisturizing Lotion',
        price: 8,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/30.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Moisturizing Lotion'],
    },
    {
        id: '31',
        name: 'Perfume',
        price: 26,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/31.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '32',
        name: 'Perfume',
        price: 30,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/32.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '33',
        name: 'Perfume',
        price: 27,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/33.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '34',
        name: 'Perfume',
        price: 29,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/34.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '35',
        name: 'Perfume',
        price: 25,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/35.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '36',
        name: 'Perfume',
        price: 28,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/36.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '37',
        name: 'Perfume',
        price: 29,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/37.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '38',
        name: 'Perfume',
        price: 29,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/38.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '39',
        name: 'Perfume',
        price: 25,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/39.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '40',
        name: 'Perfume',
        price: 28,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/40.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '41',
        name: 'Perfume',
        price: 29,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/41.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '42',
        name: 'Perfume',
        price: 29,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/42.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '43',
        name: 'Perfume',
        price: 26,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/43.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '44',
        name: 'Perfume',
        price: 27,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/44.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '45',
        name: 'Perfume',
        price: 29,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/45.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Perfume'],
    },
    {
        id: '46',
        name: 'Pressed Powder',
        price: 6,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/46.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '47',
        name: 'Pressed Powder',
        price: 8,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/47.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '48',
        name: 'Pressed Powder',
        price: 9,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/48.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '49',
        name: 'Pressed Powder',
        price: 10,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/49.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '50',
        name: 'Pressed Powder',
        price: 12,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/50.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '51',
        name: 'Pressed Powder',
        price: 14,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/51.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '52',
        name: 'Pressed Powder',
        price: 9,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/52.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '53',
        name: 'Pressed Powder',
        price: 11,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/53.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '54',
        name: 'Pressed Powder',
        price: 16,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/54.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '55',
        name: 'Pressed Powder',
        price: 18,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/55.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Pressed Powder'],
    },
    {
        id: '56',
        name: 'Face Cream',
        price: 18,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/56.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '57',
        name: 'Face Cream',
        price: 16,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/57.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '58',
        name: 'Face Cream',
        price: 19,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/58.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '59',
        name: 'Face Cream',
        price: 11,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/59.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '60',
        name: 'Face Cream',
        price: 14,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/60.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '61',
        name: 'Face Cream',
        price: 9,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/61.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '62',
        name: 'Face Cream',
        price: 10,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/62.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '63',
        name: 'Face Cream',
        price: 8,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/63.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '64',
        name: 'Face Cream',
        price: 14,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/64.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '65',
        name: 'Face Cream',
        price: 12,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/65.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Face Cream'],
    },
    {
        id: '66',
        name: 'Eye Shadow',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/66.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '67',
        name: 'Eye Shadow',
        price: 5,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/67.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '68',
        name: 'Eye Shadow',
        price: 8,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: false,
        stars: 5.0,
        imageUrl: 'assets/images/68.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '69',
        name: 'Eye Shadow',
        price: 9,
        favorite: false,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/69.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '70',
        name: 'Eye Shadow',
        price: 9,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/70.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '71',
        name: 'Eye Shadow',
        price: 4,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/71.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '72',
        name: 'Eye Shadow',
        price: 7,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/72.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '73',
        name: 'Eye Shadow',
        price: 8,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/73.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '74',
        name: 'Eye Shadow',
        price: 9,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/74.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '75',
        name: 'Eye Shadow',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/75.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '76',
        name: 'Eye Shadow',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.0,
        imageUrl: 'assets/images/76.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '77',
        name: 'Eye Shadow',
        price: 3,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/77.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '78',
        name: 'Eye Shadow',
        price: 4,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/78.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '79',
        name: 'Eye Shadow',
        price: 5,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 5.0,
        imageUrl: 'assets/images/79.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
    {
        id: '80',
        name: 'Eye Shadow',
        price: 2,
        favorite: true,
        discountPrice: 1.5,
        is_in_inventory: true,
        stars: 4.5,
        imageUrl: 'assets/images/80.jpg',
        origins: ['italy'],
        deliveryDay: '2-4',
        tags: ['Eye Shadow'],
    },
]

export const sample_tags:Tag[] = [
    { name: 'All', count: 80},
    { name: 'Mascara', count: 10},
    { name: 'Lipstick', count: 10},
    { name: 'Moisturizing Lotion', count: 10},
    { name: 'Perfume', count: 15},
    { name: 'Pressed Powder', count: 10},
    { name: 'Face Cream', count: 10},
    { name: 'Eye Shadow', count: 15}
]

